# Generated by Django 4.2.3 on 2023-08-15 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceweb', '0003_carts_category_offers_orders_products_reviews_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='expected_deliverydate',
            field=models.DateField(default=datetime.date(2023, 8, 20)),
        ),
    ]
